---
title: "Data-Clean-Up-Invert-Riparian"
author: "Jonathan Ray"
date: "2023-02-27"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
library(dplyr)
library(tidyr)
library(ggplot2)
library(lubridate)
library(readr)
```


```{r datasets Jonathan}
data11 <- read.csv("../data/processed/D08 MAYF/NEON.D08.MAYF.DP1.20120.001.inv_taxonomyProcessed.2017-07.expanded.20221122T184910Z.csv")
data12 <- read.csv("../data/processed/D08 MAYF/NEON.D08.MAYF.DP1.20120.001.inv_taxonomyProcessed.2018-07.expanded.20221128T184824Z.csv")
data13 <- read.csv("../data/processed/D08 MAYF/NEON.D08.MAYF.DP1.20120.001.inv_taxonomyProcessed.2019-07.expanded.20221128T173134Z.csv")
data14 <- read.csv("../data/processed/D08 MAYF/NEON.D08.MAYF.DP1.20120.001.inv_taxonomyProcessed.2020-07.expanded.20221128T212351Z.csv")
data15 <- read.csv("../data/processed/D08 MAYF/NEON.D08.MAYF.DP1.20120.001.inv_taxonomyProcessed.2021-07.expanded.20221129T232348Z.csv")
data16 <- read.csv("../data/processed/D08 MAYF/NEON.D08.MAYF.DP1.20191.001.rip_percentComposition.2017-08.basic.20230112T002045Z.csv")
data17 <- read.csv("../data/processed/D08 MAYF/NEON.D08.MAYF.DP1.20191.001.rip_percentComposition.2018-08.basic.20230112T002023Z.csv")
data18 <- read.csv("../data/processed/D08 MAYF/NEON.D08.MAYF.DP1.20191.001.rip_percentComposition.2019-08.basic.20230112T001825Z.csv")
data19 <- read.csv("../data/processed/D08 MAYF/NEON.D08.MAYF.DP1.20191.001.rip_percentComposition.2021-08.basic.20230112T002158Z.csv")
data110 <- read.csv("../data/processed/D08 MAYF/NEON.D08.MAYF.DP1.20191.001.rip_percentComposition.2022-08.basic.20230112T002125Z.csv")

```

```{r dataset Callie}
data21 <- read.csv("../data/processed/D17 BIGC/NEON.D17.BIGC.DP1.20120.001.inv_taxonomyProcessed.2018-07.expanded.20221128T191616Z.csv")
data22 <- read.csv("../data/processed/D17 BIGC/NEON.D17.BIGC.DP1.20120.001.inv_taxonomyProcessed.2019-07.expanded.20221128T162452Z 2.csv")
data23 <- read.csv("../data/processed/D17 BIGC/NEON.D17.BIGC.DP1.20120.001.inv_taxonomyProcessed.2021-07.expanded.20221129T222632Z.csv")
data24 <- read.csv("../data/processed/D17 BIGC/NEON.D17.BIGC.DP1.20191.001.rip_percentComposition.2018-07.basic.20230112T002002Z.csv")
data25 <- read.csv("../data/processed/D17 BIGC/NEON.D17.BIGC.DP1.20191.001.rip_percentComposition.2019-07.basic.20230112T002213Z.csv")
data26 <- read.csv("../data/processed/D17 BIGC/NEON.D17.BIGC.DP1.20191.001.rip_percentComposition.2021-08.basic.20230112T001807Z.csv")
data27 <- read.csv("../data/processed/D17 BIGC/NEON.D17.BIGC.DP1.20191.001.rip_percentComposition.2021-08.basic.20230112T001807Z.csv")
```

```{r datasets Chelsey}
data31 <- read.csv("../data/processed/D18 OKSR/NEON.D18.OKSR.DP1.20120.001.inv_taxonomyProcessed.2017-07.expanded.20221122T171622Z.csv")
data32 <- read.csv("../data/processed/D18 OKSR/NEON.D18.OKSR.DP1.20120.001.inv_taxonomyProcessed.2018-07.expanded.20221128T182544Z.csv")
data33 <- read.csv("../data/processed/D18 OKSR/NEON.D18.OKSR.DP1.20120.001.inv_taxonomyProcessed.2019-07.expanded.20221128T174721Z.csv")
data34 <- read.csv("../data/processed/D18 OKSR/NEON.D18.OKSR.DP1.20120.001.inv_taxonomyProcessed.2020-07.expanded.20221128T220306Z.csv")
data35 <- read.csv("../data/processed/D18 OKSR/NEON.D18.OKSR.DP1.20120.001.inv_taxonomyProcessed.2021-07.expanded.20221129T222833Z.csv")
data36 <- read.csv("../data/processed/D18 OKSR/NEON.D18.OKSR.DP1.20191.001.rip_percentComposition.2017-07.basic.20230112T002307Z.csv")
data37 <- read.csv("../data/processed/D18 OKSR/NEON.D18.OKSR.DP1.20191.001.rip_percentComposition.2019-07.basic.20230112T001757Z.csv")
data38 <- read.csv("../data/processed/D18 OKSR/NEON.D18.OKSR.DP1.20191.001.rip_percentComposition.2021-07.basic.20230112T002024Z.csv")
data39 <- read.csv("../data/processed/D18 OKSR/NEON.D18.OKSR.DP1.20191.001.rip_percentComposition.2022-07.basic.20230112T001943Z.csv")

```

```{r combined}
all_macroinvert <- bind_rows(data11,data12,data13,data14,data15,data21,data22,data23,data31,data32,data33,data34,data35)
all_macroinvert_year <- all_macroinvert %>% 
  mutate(year = floor_date(as.Date(collectDate), unit = "year")) %>% 
  group_by(siteID, year) %>% 
  select("siteID", "genus", "year")
all_riparian <- bind_rows(data16,data17,data18,data19,data110,data24,data25,data26,data27,data36,data37,data38,data39)
all_riparian_year <- all_riparian %>% 
  mutate(year = floor_date(as.Date(startDate), unit = "year")) %>% 
  group_by(siteID, year) %>% 
  select("siteID", "canopyCoverPercent", "year")
combined_data <- left_join(all_macroinvert_year,all_riparian_year, by = c("siteID","year")) %>% 
  relocate(year, .before = siteID)

```

```{r histogram}
combined_data %>% 
  ggplot(aes(x=canopyCoverPercent)) +
  geom_histogram()

```

```{r grouping}
combined_data_group <- combined_data %>% 
  group_by(siteID, year) %>% 
  summarise(species.richness = unique(length(genus)), cover.average = mean(canopyCoverPercent))

```

```{r visualization}

```

```{r second vis}

```

```{r stats}

```